### ISSUE TITLE
WinUI3 WindowsAppSDK1.X doesn't support SwapChainPanel

### ISSUE THREAD

**Issue by scrtkr** [MicrosoftDocs/winapps-winrt-api#10]
WinUI 3, Windows App SDK 1.x

https://learn.microsoft.com/en-us/windows/uwp/gaming/directx-and-xaml-interop
I tested the SwapChainPanel in C++/WinRT project like above code for SwapChainPanel.
But in WinUI 3, Windows App SDK 1.x, above code for SwapChainPanel happened runtime error.

Doesn't WinUI3 support SwapChainPanel?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c62bb23b-3db6-4bce-7990-02d13db27aea
* Version Independent ID: c62bb23b-3db6-4bce-7990-02d13db27aea
* Content: [SwapChainPanel Class (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.swapchainpanel?view=windows-app-sdk-1.1)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/SwapChainPanel.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/SwapChainPanel.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @alexlozdev, and thanks for filing this issue. That topic applies only to UWP apps, by the way.

Back in the Windows App SDK 0.8.1 timeframe, I tried doing the same thing (using a SwapChainPanel) with a WinUI 3 app, and using Direct3D 11-on-12. I had some success with it, but it wasn't perfect IIRC. My project (https://github.com/stevewhims/D3D11On12WinUI) is way out of date now, but there it is in case it's useful. However, I do remember being told that folks were surprised it worked as well as it did, since SwapChainPanel is NOT the right approach for a WinUI 3 app (at least, it wasn't at the time).

But for product questions such as that, you'll likely be able to get a more definitive and up to date answer if you ask on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html). That's the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.

Thanks!
-Steve
