### ISSUE TITLE
There should be a link that directly navigate to a style for this control. 

### ISSUE THREAD

**Issue by KWodarczyk** [MicrosoftDocs/winapps-winrt-api#23]
Control style and template
this section should have links to pages that contain actual default style for NavigationView, NavigationViewItems etc.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe5f49ee-6f6f-b9eb-ab09-42bb2f10b2b6
* Version Independent ID: fe5f49ee-6f6f-b9eb-ab09-42bb2f10b2b6
* Content: [NavigationView Class (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.navigationview?view=windows-app-sdk-1.2)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/NavigationView.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/NavigationView.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for this feedback. In the past, we've attempted to provide links to pages that contain the XAML for the control template, but because it can change from one version to the next, it becomes extremely difficult to maintain over time. We now provide information about how to find the template locally for the specific version of the control that you're using.
