### ISSUE TITLE
Missing Methods and Events dorpdown on right hand nav for slider and probably other items

### ISSUE THREAD

**Issue by KWodarczyk** [MicrosoftDocs/winapps-winrt-api#69]
Missing Methods and Events dorpdown on right hand nav for slider and probably other items

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 320ba237-6463-5eeb-0685-456f6b141e9c
* Version Independent ID: 320ba237-6463-5eeb-0685-456f6b141e9c
* Content: [Slider Class (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.slider?view=windows-app-sdk-1.3)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/Slider.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/Slider.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This is by design. The Table of Contents (TOC) navigation includes only the direct members of a class, but not inherited members. All the methods and events for Slider are inherited, so they are listed only in the tables on the class page, but not in the TOC navigation. (The number of inherited members can be very large, which makes the TOC navigation difficult to use if they are all listed there.)

**Comment by KWodarczyk** [comment]
Not sure if this is good user experience
